### ISSUE TITLE
cpp_extension error

### ISSUE THREAD

**Issue by TonyzBi** [zzyunzhi/object-intrinsics#1]
Thanks for your great jobs, but when I try to run trainning code , it gives me the following error:
A10-Server:~/projects/object-intrinsics$ pip install -e .
Obtaining file:///home/bihai/projects/object-intrinsics
  Preparing metadata (setup.py) ... done
Installing collected packages: objint
  Running setup.py develop for objint
Successfully installed objint-0.0.0
(LLM) bihai@A10-Server:~/projects/object-intrinsics$ python scripts/train.py -d data/example
INFO:__main__:{"overwrite": false, "seed": 0, "tag": null, "dataset": "data/example", "config": "train", "log_unique": false, "opts": []}
INFO:tu.train_setup:setting seed 0
INFO:tu.train.setup:set environ: DEBUG: None -> 0
INFO:tu.utils.config:overwrite key dataset: None -> data/example
INFO:tu.utils.config:overwrite key log_dir: None -> logs/_data_example_train
INFO:tu.utils.config:overwrite key scene_fov: None -> 56.97764364679225
INFO:tu.utils.config:overwrite key cam_dist: None -> 11.430052302761343
INFO:__main__:found render config:
{"b2w_scene_prior": {"__target__": "src.utils.pose_sampler.Plane", "kwargs": {"cam_loc": [0, -1, 0], "rot_degree_range_scale": 360, "rot_roll_degree_range_scale": 20, "xy_range_scale": [6, 3.5]}}, "fov": 10, "img_size": 256, "img_size_scene": 1588, "cam_dist": 11.430052302761343, "scene_fov": 56.97764364679225}
INFO:tu.utils.config:overwrite key scene_fov: None -> 56.97764364679225
INFO:tu.utils.config:overwrite key fov: None -> 10
INFO:tu.utils.config:overwrite key cam_dist: None -> 11.430052302761343
INFO:tu.utils.config:overwrite key pose_prior: None -> {'__target__': 'src.utils.pose_sampler.Plane', 'kwargs': {'cam_loc': [0, -1, 0], 'rot_degree_range_scale': 360, 'rot_roll_degree_range_scale': 20, 'xy_range_scale': [6, 3.5]}}
WARNING:__main__:no l2w_scene_prior in render_config, use collocated light
INFO:tu.utils.config:overwrite key scene_resolution: None -> 794
INFO:tu.utils.config:overwrite key runtime: None -> {'slurm_job_id': None, 'slurm_job_name': None}
INFO:tu.utils.config:overwrite key args: None -> {'overwrite': False, 'seed': 0, 'tag': None, 'dataset': 'data/example', 'config': 'train', 'log_unique': False, 'opts': []}
INFO:tu.utils.config:overwrite key argv: None -> ['scripts/train.py', '-d', 'data/example']
INFO:src.datasets.eval_dataset:found 28 images in data/example
INFO:src.models.camera_network:create camera with focal: 731.523347376726 and cam_dist: 11.430052302761343
INFO:src.utils.prior:build light with direction: [ 0.  0. -1.]
WARNING:src.utils.pose:special case for look at: eye tensor([ 0., -1.,  0.]), center tensor([0., 0., 0.]), up tensor([0., 1., 0.])
WARNING:src.utils.pose:special case for look at: eye tensor([ 0., -1.,  0.]), center tensor([0., 0., 0.]), up tensor([0., 1., 0.])
Traceback (most recent call last):
  File "/home/bihai/projects/object-intrinsics/scripts/train.py", line 213, in <module>
    main()
  File "/home/bihai/projects/object-intrinsics/scripts/train.py", line 182, in main
    get_model(key)
  File "/home/bihai/projects/object-intrinsics/scripts/train.py", line 151, in get_model
    model = build_from_config(cfg['model'][key], **kwargs)
  File "/home/bihai/projects/object-intrinsics/tu/utils/config.py", line 25, in build_from_config
    return obj(**config['kwargs'], **kwargs)
  File "/home/bihai/projects/object-intrinsics/src/models/generator.py", line 45, in __init__
    self.color_network = build_from_config(color_network)
  File "/home/bihai/projects/object-intrinsics/tu/utils/config.py", line 24, in build_from_config
    obj = get_obj_from_str(config['__target__'])
  File "/home/bihai/projects/object-intrinsics/tu/utils/config.py", line 16, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "/home/bihai/anaconda3/envs/LLM/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/bihai/projects/object-intrinsics/src/models/fields.py", line 6, in <module>
    from ..third_party.stylesdf.model import MappingLinear
  File "/home/bihai/projects/object-intrinsics/src/third_party/stylesdf/model.py", line 9, in <module>
    from .op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/home/bihai/projects/object-intrinsics/src/third_party/stylesdf/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/home/bihai/projects/object-intrinsics/src/third_party/stylesdf/op/fused_act.py", line 11, in <module>
    fused = load(
  File "/home/bihai/anaconda3/envs/LLM/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/bihai/anaconda3/envs/LLM/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/bihai/anaconda3/envs/LLM/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1593, in _write_ninja_file_and_build_library
    verify_ninja_availability()
  File "/home/bihai/anaconda3/envs/LLM/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1649, in verify_ninja_availability
    raise RuntimeError("Ninja is required to load C++ extensions")
RuntimeError: Ninja is required to load C++ extensions

could you give me some advices about how to build the third extension in this project.

**Comment by TonyzBi** [comment]
solved : pip install ninja and install CUDA 11.7, set CUDA_HOME.

**Comment by zzyunzhi** [comment]
Glad you solved it! Closing the issue for now, but feel free to reopen it if the error persists.
